//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "ContactsPage.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
 #include <drogon/HttpRequest.h> 
using namespace drogon;
std::string ContactsPage::genText(const DrTemplateData& ContactsPage_view_data)
{
	drogon::OStringStream ContactsPage_tmp_stream;
	std::string layoutName{""};
	ContactsPage_tmp_stream << "<%inc #include <string> %>\n";
 auto &req = ContactsPage_view_data.get<HttpRequestPtr>("req"); 
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "<head>\n";
	ContactsPage_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	ContactsPage_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	ContactsPage_tmp_stream << "    <title>Contact Us - Drogon Site</title>\n";
	ContactsPage_tmp_stream << "    <link rel=\"stylesheet\" href=\"/css/styles.css\">\n";
	ContactsPage_tmp_stream << "</head>\n";
	ContactsPage_tmp_stream << "<body>\n";
	ContactsPage_tmp_stream << "    <header>\n";
	ContactsPage_tmp_stream << "        <nav>\n";
	ContactsPage_tmp_stream << "            <div class=\"logo\">Drogon Site</div>\n";
	ContactsPage_tmp_stream << "            <ul class=\"nav-links\">\n";
	ContactsPage_tmp_stream << "                <li><a href=\"/\">Home</a></li>\n";
	ContactsPage_tmp_stream << "                <li><a href=\"/about\">About</a></li>\n";
	ContactsPage_tmp_stream << "                <li><a href=\"/services\">Services</a></li>\n";
	ContactsPage_tmp_stream << "                <li><a href=\"/contact\">Contact</a></li>\n";
	ContactsPage_tmp_stream << "            </ul>\n";
	ContactsPage_tmp_stream << "        </nav>\n";
	ContactsPage_tmp_stream << "    </header>\n";
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "    <div class=\"container\">\n";
	ContactsPage_tmp_stream << "        <main>\n";
	ContactsPage_tmp_stream << "            <h1>";
{
    auto & val=ContactsPage_view_data["title"];
    if(val.type()==typeid(const char *)){
        ContactsPage_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        ContactsPage_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	ContactsPage_tmp_stream << "</h1>\n";
	ContactsPage_tmp_stream << "            ";
 if(req->getParameter("status") == "success") { 
	ContactsPage_tmp_stream << "                <div class=\"success-message\">Your message has been sent successfully!</div>\n";
	ContactsPage_tmp_stream << "            ";
 } 
	ContactsPage_tmp_stream << "            \n";
	ContactsPage_tmp_stream << "            <section class=\"content-section\">\n";
	ContactsPage_tmp_stream << "                <h2>Get in Touch</h2>\n";
	ContactsPage_tmp_stream << "                <form class=\"contact-form\" action=\"/contact\" method=\"POST\">\n";
	ContactsPage_tmp_stream << "                    <div class=\"form-group\">\n";
	ContactsPage_tmp_stream << "                        <label for=\"name\">Name:</label>\n";
	ContactsPage_tmp_stream << "                        <input type=\"text\" id=\"name\" name=\"username\" required>\n";
	ContactsPage_tmp_stream << "                    </div>\n";
	ContactsPage_tmp_stream << "                    <div class=\"form-group\">\n";
	ContactsPage_tmp_stream << "                        <label for=\"email\">Email:</label>\n";
	ContactsPage_tmp_stream << "                        <input type=\"email\" id=\"email\" name=\"email\" required>\n";
	ContactsPage_tmp_stream << "                    </div>\n";
	ContactsPage_tmp_stream << "                    <div class=\"form-group\">\n";
	ContactsPage_tmp_stream << "                        <label for=\"message\">Message:</label>\n";
	ContactsPage_tmp_stream << "                        <textarea id=\"message\" name=\"message\" rows=\"5\" required></textarea>\n";
	ContactsPage_tmp_stream << "                    </div>\n";
	ContactsPage_tmp_stream << "                    <button type=\"submit\" class=\"submit-btn\">Send Message</button>\n";
	ContactsPage_tmp_stream << "                </form>\n";
	ContactsPage_tmp_stream << "            </section>\n";
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "            <section class=\"content-section\">\n";
	ContactsPage_tmp_stream << "                <h2>Office Location</h2>\n";
	ContactsPage_tmp_stream << "                <p>123 Technology Park<br>\n";
	ContactsPage_tmp_stream << "                   Silicon Valley, CA 94025<br>\n";
	ContactsPage_tmp_stream << "                   United States\n";
	ContactsPage_tmp_stream << "                </p>\n";
	ContactsPage_tmp_stream << "            </section>\n";
	ContactsPage_tmp_stream << "        </main>\n";
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "        <aside class=\"sidebar\">\n";
	ContactsPage_tmp_stream << "            <h3>Contact Information</h3>\n";
	ContactsPage_tmp_stream << "            <div class=\"sidebar-content\">\n";
	ContactsPage_tmp_stream << "                <div class=\"update-item\">\n";
	ContactsPage_tmp_stream << "                    <h4>Business Hours</h4>\n";
	ContactsPage_tmp_stream << "                    <p>Monday - Friday: 9AM - 6PM<br>\n";
	ContactsPage_tmp_stream << "                       Saturday: 10AM - 2PM</p>\n";
	ContactsPage_tmp_stream << "                </div>\n";
	ContactsPage_tmp_stream << "                <div class=\"update-item\">\n";
	ContactsPage_tmp_stream << "                    <h4>Phone</h4>\n";
	ContactsPage_tmp_stream << "                    <p>Main: (555) 123-4567<br>\n";
	ContactsPage_tmp_stream << "                       Support: (555) 987-6543</p>\n";
	ContactsPage_tmp_stream << "                </div>\n";
	ContactsPage_tmp_stream << "                <div class=\"update-item\">\n";
	ContactsPage_tmp_stream << "                    <h4>Email</h4>\n";
	ContactsPage_tmp_stream << "                    <p>info@example.com<br>\n";
	ContactsPage_tmp_stream << "                       support@example.com\n";
	ContactsPage_tmp_stream << "                    </p>\n";
	ContactsPage_tmp_stream << "                </div>\n";
	ContactsPage_tmp_stream << "            </div>\n";
	ContactsPage_tmp_stream << "        </aside>\n";
	ContactsPage_tmp_stream << "    </div>\n";
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "    <footer>\n";
	ContactsPage_tmp_stream << "        <div class=\"footer-content\">\n";
	ContactsPage_tmp_stream << "            <div class=\"footer-section\">\n";
	ContactsPage_tmp_stream << "                <h4>Contact Us</h4>\n";
	ContactsPage_tmp_stream << "                <p>Email: magpinyb@proton.me</p>\n";
	ContactsPage_tmp_stream << "                <p>Phone: (555) 123-4567</p>\n";
	ContactsPage_tmp_stream << "            </div>\n";
	ContactsPage_tmp_stream << "            <div class=\"footer-section\">\n";
	ContactsPage_tmp_stream << "                <p id=\"current-date\"></p>\n";
	ContactsPage_tmp_stream << "            </div>\n";
	ContactsPage_tmp_stream << "        </div>\n";
	ContactsPage_tmp_stream << "    </footer>\n";
ContactsPage_tmp_stream<<"\n";
	ContactsPage_tmp_stream << "    <script src=\"/js/app.js\"></script>\n";
	ContactsPage_tmp_stream << "</body>\n";
	ContactsPage_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(ContactsPage_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = ContactsPage_view_data;
auto str = std::move(ContactsPage_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
