//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class ContactsPage:public drogon::DrTemplate<ContactsPage>
{
public:
	ContactsPage(){};
	virtual ~ContactsPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
