//this file is generated by program(drogon_ctl) automatically,don't modify it!
#include "HomePage.h"
#include <drogon/utils/OStringStream.h>
#include <string>
#include <map>
#include <vector>
#include <set>
#include <iostream>
#include <unordered_map>
#include <unordered_set>
#include <algorithm>
#include <list>
#include <deque>
#include <queue>
using namespace drogon;
std::string HomePage::genText(const DrTemplateData& HomePage_view_data)
{
	drogon::OStringStream HomePage_tmp_stream;
	std::string layoutName{""};
	HomePage_tmp_stream << "<!DOCTYPE html>\n";
	HomePage_tmp_stream << "<html lang=\"en\">\n";
	HomePage_tmp_stream << "<head>\n";
	HomePage_tmp_stream << "    <meta charset=\"UTF-8\">\n";
	HomePage_tmp_stream << "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n";
	HomePage_tmp_stream << "    <title>";
{
    auto & val=HomePage_view_data["title"];
    if(val.type()==typeid(const char *)){
        HomePage_tmp_stream<<*(std::any_cast<const char *>(&val));
    }else if(val.type()==typeid(std::string)||val.type()==typeid(const std::string)){
        HomePage_tmp_stream<<*(std::any_cast<const std::string>(&val));
    }
}
	HomePage_tmp_stream << "</title>\n";
	HomePage_tmp_stream << "    <link rel=\"stylesheet\" href=\"/css/styles.css\">\n";
	HomePage_tmp_stream << "</head>\n";
	HomePage_tmp_stream << "<body>\n";
	HomePage_tmp_stream << "    <header>\n";
	HomePage_tmp_stream << "        <nav>\n";
	HomePage_tmp_stream << "            <div class=\"logo\">Drogon Site</div>\n";
	HomePage_tmp_stream << "            <ul class=\"nav-links\">\n";
	HomePage_tmp_stream << "                <li><a href=\"/\">Home</a></li>\n";
	HomePage_tmp_stream << "                <li><a href=\"/about\">About</a></li>\n";
	HomePage_tmp_stream << "                <li><a href=\"/services\">Services</a></li>\n";
	HomePage_tmp_stream << "                <li><a href=\"/contact\">Contact</a></li>\n";
	HomePage_tmp_stream << "            </ul>\n";
	HomePage_tmp_stream << "        </nav>\n";
	HomePage_tmp_stream << "    </header>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "    <div class=\"container\">\n";
	HomePage_tmp_stream << "        <main>\n";
	HomePage_tmp_stream << "            <h1>Welcome to Our Website</h1>\n";
	HomePage_tmp_stream << "            \n";
	HomePage_tmp_stream << "            <section class=\"content-section\">\n";
	HomePage_tmp_stream << "                <h2>Innovation at Its Best</h2>\n";
	HomePage_tmp_stream << "                <p>In today's rapidly evolving digital landscape, staying ahead means embracing cutting-edge technologies and innovative solutions. Our platform leverages the power of modern web technologies to deliver exceptional performance and reliability.</p>\n";
	HomePage_tmp_stream << "            </section>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "            <section class=\"content-section\">\n";
	HomePage_tmp_stream << "                <h2>Building the Future</h2>\n";
	HomePage_tmp_stream << "                <p>\n";
	HomePage_tmp_stream << "                    We believe in creating sustainable, scalable solutions that not only meet current needs but are also prepared for future challenges. Our team of experts works tirelessly to ensure we're always at the forefront of technological advancement.\n";
	HomePage_tmp_stream << "                </p>\n";
	HomePage_tmp_stream << "            </section>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "            <section class=\"content-section\">\n";
	HomePage_tmp_stream << "                <h2>Community Driven</h2>\n";
	HomePage_tmp_stream << "                <p>\n";
	HomePage_tmp_stream << "                    Our success is built on the foundation of a strong community. We value collaboration, open communication, and continuous improvement, working together to create solutions that make a real difference in people's lives.\n";
	HomePage_tmp_stream << "                </p>\n";
	HomePage_tmp_stream << "                <big> \n";
	HomePage_tmp_stream << "                    To whoever seeing this, this is a C++ Website and for you see this website the owner has undergone a \n";
	HomePage_tmp_stream << "                    series of cmake and config.json file configs before fighting docker and build environment configs before deploying it. \n";
	HomePage_tmp_stream << "                </big>\n";
	HomePage_tmp_stream << "                <small> \n";
	HomePage_tmp_stream << "                    TODO: server side code using postgres as a database. This site will evolve into something i don't know provided   I have time to explore. \n";
	HomePage_tmp_stream << "                </small>\n";
	HomePage_tmp_stream << "                <h3>I'm just curious to learn how C++ can be used in web development</h3>\n";
	HomePage_tmp_stream << "            </section>\n";
	HomePage_tmp_stream << "        </main>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "        <aside class=\"sidebar\">\n";
	HomePage_tmp_stream << "            <h3>Latest Updates</h3>\n";
	HomePage_tmp_stream << "            <div class=\"sidebar-content\">\n";
	HomePage_tmp_stream << "                <div class=\"update-item\">\n";
	HomePage_tmp_stream << "                    <h4>New Features Released</h4>\n";
	HomePage_tmp_stream << "                    <p>Check out our latest platform updates!</p>\n";
	HomePage_tmp_stream << "                </div>\n";
	HomePage_tmp_stream << "                <div class=\"update-item\">\n";
	HomePage_tmp_stream << "                    <h4>Upcoming Events</h4>\n";
	HomePage_tmp_stream << "                    <p>Join our next webinar series.</p>\n";
	HomePage_tmp_stream << "                </div>\n";
	HomePage_tmp_stream << "                <div class=\"update-item\">\n";
	HomePage_tmp_stream << "                    <h4>Community News</h4>\n";
	HomePage_tmp_stream << "                    <p>See what our community has been up to.</p>\n";
	HomePage_tmp_stream << "                </div>\n";
	HomePage_tmp_stream << "            </div>\n";
	HomePage_tmp_stream << "        </aside>\n";
	HomePage_tmp_stream << "    </div>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "    <footer>\n";
	HomePage_tmp_stream << "        <div class=\"footer-content\">\n";
	HomePage_tmp_stream << "            <div class=\"footer-section\">\n";
	HomePage_tmp_stream << "                <h4>Contact Us</h4>\n";
	HomePage_tmp_stream << "                <p>Email: magpinyb@proton.me</p>\n";
	HomePage_tmp_stream << "                <p>Phone: (555) 123-4567</p>\n";
	HomePage_tmp_stream << "            </div>\n";
	HomePage_tmp_stream << "            <div class=\"footer-section\">\n";
	HomePage_tmp_stream << "                <p id=\"current-date\"></p>\n";
	HomePage_tmp_stream << "            </div>\n";
	HomePage_tmp_stream << "        </div>\n";
	HomePage_tmp_stream << "    </footer>\n";
HomePage_tmp_stream<<"\n";
	HomePage_tmp_stream << "    <script src=\"/js/app.js\"></script>\n";
	HomePage_tmp_stream << "</body>\n";
	HomePage_tmp_stream << "</html>\n";
if(layoutName.empty())
{
std::string ret{std::move(HomePage_tmp_stream.str())};
return ret;
}else
{
auto templ = DrTemplateBase::newTemplate(layoutName);
if(!templ) return "";
HttpViewData data = HomePage_view_data;
auto str = std::move(HomePage_tmp_stream.str());
if(!str.empty() && str[str.length()-1] == '\n') str.resize(str.length()-1);
data[""] = std::move(str);
return templ->genText(data);
}
}
