//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class registration:public drogon::DrTemplate<registration>
{
public:
	registration(){};
	virtual ~registration(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
